language: python

#test agains python 2
python:
  - "2.7"

#cache pip
cache: pip

#install dependacies
install:
  - pip install -r requirements.txt

#run test using nose
script: nosetests tests

notifications:
  email: false