language: python

#test agains python 2
python:
  - "2.7"

#cache pip
cache: pip

#install dependacies
install:
  - pip install -r requirements.txt
  - pip install codeclimate-test-reporter

#run test using nose
script:
  nosetests --with-coverage --cover-erase

after_success:
  codeclimate-test-reporter

notifications:
  email: false